fix(epoch): use epochZeroStartTimestamp to determine if you should try and submit a report
The current error:
```
error: Error generating report Cannot destructure property "startTimestamp" of "(intermediate value)" as it is undefined.
```

happens because we expect epoch to be defined in the ContractSource. If we have not created any epochs, this destructing results in undefined values. By checking the epochZeroStartTimestamp beofre attempting to fetch an epoch, we clean up the error.